# Generated by Django 2.0.2 on 2018-08-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
